# sudo: false
sudo: required
dist: trusty

language: python

python:
    - "2.7"
    #- "3.2"

virtualenv:
  system_site_packages: true

# install dependencies
before_install:
  - sudo add-apt-repository -y ppa:nschloe/eigen-nightly
  - sudo apt-add-repository -y ppa:nschloe/cmake-backports
  - sudo apt-add-repository -y ppa:nschloe/swig-backports
  - sudo apt update -qq
  - sudo apt-get -y install cmake libcgal-dev libeigen3-dev swig

install:
  - cmake .
  - make install

script:
  - cd test
  - nosetests
