# sudo: false
sudo: required
dist: trusty

language: python

python:
    - "2.7"
    #- "3.2"

virtualenv:
  system_site_packages: true

# install dependencies
before_install:
  - sudo apt-get -y install libcgal-dev libeigen3-dev

install:
  - cmake .
  - make install

script:
  - cd test
  - nosetests
