version: 2

jobs:

  build:
    working_directory: ~/pygalmesh
    docker:
      - image: ubuntu:17.04
    steps:
      - run: apt-get update
      - run: apt-get install -y libcgal-dev libeigen3-dev pandoc python3-pip
      - run: pip3 install -U pytest pytest-cov pylint meshio
      - checkout
      # install
      - run: LANG=C.UTF-8 pip3 install .
      # lint
      - run: pylint setup.py
      # The actual test
      - run: cd test/ && pytest
