version: 2

jobs:

  build:
    working_directory: ~/pygalmesh
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt-get update
      - run: apt-get install -y libcgal-dev libeigen3-dev pandoc python3-pip
      - run: pip3 install -U pytest pytest-cov pylint meshio
      - checkout
      # lint
      - run: pylint setup.py test/*.py
      # make sure that rst converts correctly
      - run: pip3 install docutils pygments
      - run: make README.rst
      # install
      - run: pip3 install .
      # The actual test
      - run: cd test/ && pytest
