version: 2

jobs:

#   python2:
#     working_directory: ~/frentos
#     docker:
#       - image: ubuntu:17.04
#     steps:
#       - run: apt-get update
#       - run: apt-get install -y git gmsh python-pip python-matplotlib python-numpy python-scipy
#       - run: pip2 install -U pytest pytest-cov pylint code_extract
#       - checkout
#       - run: LANG=C.UTF-8 pip2 install .
#       # lint
#       - run: pylint frentos/
#       - run: pylint test/examples/*py
#       # The tests
#       - run: code_extract README.md test/readme_test.py --filter python,test
#       - run: cd test/ && MPLBACKEND=Agg pytest --cov frentos

#  python3:
  build:
    working_directory: ~/frentos
    docker:
      - image: ubuntu:17.04
    steps:
      - run: apt-get update
      - run: apt-get install -y libcgal-dev libeigen3-dev pandoc python3-numpy python3-pip
      - run: pip3 install -U pytest pytest-cov pylint meshio
      - checkout
      # install
      - run: LANG=C.UTF-8 pip3 install .
      # lint
      - run: pylint setup.py
      # The actual test
      - run: cd test/ && pytest

# workflow builds don't support forked PRs yet, cf.
# <https://circleci.com/docs/2.0/faq/#can-i-build-fork-prs-using-workflows>.
# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - python2
#       - python3
